services:
  gmaps:
    image: gosom/google-maps-scraper:latest
    restart: unless-stopped

    command:
      - "-data-folder"
      - "/gmapsdata"
      - "-proxies"
      - "${31.59.20.176:6754:rmdvpdrd:jzveketuhsk6,31.56.127.193:7684:rmdvpdrd:jzveketuhsk6,45.38.107.97:6014:rmdvpdrd:jzveketuhsk6,198.105.121.200:6462:rmdvpdrd:jzveketuhsk6,64.137.96.74:6641:rmdvpdrd:jzveketuhsk6,198.23.243.226:6361:rmdvpdrd:jzveketuhsk6,38.154.185.97:6370:rmdvpdrd:jzveketuhsk6,84.247.60.125:6095:rmdvpdrd:jzveketuhsk6,142.111.67.146:5611:rmdvpdrd:jzveketuhsk6,191.96.254.138:6185:rmdvpdrd:jzveketuhsk6}"

    environment:
        DISABLE_TELEMETRY: "1"

    volumes:
      - gmaps_data:/gmapsdata

    expose:
      - "8080"

    shm_size: "1gb"
    mem_limit: "2g"
    cpus: 1

  frontend:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    depends_on:
      - gmaps

    expose:
      - "80"

    mem_limit: "256m"
    cpus: 0.50

volumes:
  gmaps_data:
